/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.CallableStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author josel
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    private final String DBURL
            = "jdbc:sqlserver://3.150.63.179;"
            + "databaseName=EXAMPLE1;"
            + "encrypt=true;"
            + "trustServerCertificate=true;"
            + "user=Administrator;"
            + "password=Wn!.CdNmhZG6pz$c+jKRVqHxAwtX9%<ysgU8k5J>M72SEYDTB&;";

    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        // Registro del driver
        try {
            DriverManager.registerDriver(new com.microsoft.sqlserver.jdbc.SQLServerDriver());
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnSelect = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnSelectMalo = new javax.swing.JButton();
        btnSelectBueno = new javax.swing.JButton();
        txtIdUpdate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNuevoNombre = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        btnSPInsert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnSelectMalo.setText("Select Malo");
        btnSelectMalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectMaloActionPerformed(evt);
            }
        });

        btnSelectBueno.setText("Select Bueno");
        btnSelectBueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectBuenoActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel2.setText("Nuevo Nombre");

        btnUpdate.setText("Update Nombre");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel3.setText("Nueva Categoria");

        btnSPInsert.setText("SP Insert");
        btnSPInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelect)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectMalo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectBueno))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210)
                        .addComponent(btnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCategoria))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSPInsert)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSelect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectMalo)
                    .addComponent(btnSelectBueno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSPInsert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        try {
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("ID");
            dtm.addColumn("Nombre");
            dtm.addColumn("Telefono");
            dtm.addColumn("Correo");
            dtm.addColumn("Calle");
            dtm.addColumn("Ciudad");
            dtm.addColumn("Estado");
            dtm.addColumn("C.P.");

            Connection con = DriverManager.getConnection(DBURL);
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery(
                    "SELECT store_id, store_name, phone, email, street, "
                    + "city, state, zip_code FROM sales.stores;"
            );

            while (rs.next()) {
                int str1 = rs.getInt(1);
                String str2 = rs.getString(2);
                String str3 = rs.getString(3);
                String str4 = rs.getString(4);
                String str5 = rs.getString(5);
                String str6 = rs.getString(6);
                String str7 = rs.getString(7);
                String str8 = rs.getString(8);
                dtm.addRow(new Object[]{str1, str2, str3, str4, str5,
                    str6, str7, str8});
            }

            this.tabla.setModel(dtm);
            rs.close();
            state.close();
            con.close();
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnSelectMaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectMaloActionPerformed
        try {
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("ID");
            dtm.addColumn("Nombre");
            dtm.addColumn("Apellido");
            dtm.addColumn("Telefono");
            dtm.addColumn("Correo");
            dtm.addColumn("Calle");
            dtm.addColumn("Ciudad");
            dtm.addColumn("Estado");
            dtm.addColumn("C.P.");

            Connection con = DriverManager.getConnection(DBURL);
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery(
                    "SELECT customer_id, first_name, last_name, phone, email, street, "
                    + "city, state, zip_code FROM sales.customers "
                    + "WHERE customer_id = " + this.txtId.getText()
            );

            while (rs.next()) {
                int str1 = rs.getInt(1);
                String str2 = rs.getString(2);
                String str3 = rs.getString(3);
                String str4 = rs.getString(4);
                String str5 = rs.getString(5);
                String str6 = rs.getString(6);
                String str7 = rs.getString(7);
                String str8 = rs.getString(8);
                String str9 = rs.getString(9);
                dtm.addRow(new Object[]{str1, str2, str3, str4, str5,
                    str6, str7, str8, str9});
            }

            this.tabla.setModel(dtm);
            rs.close();
            state.close();
            con.close();
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelectMaloActionPerformed

    private void btnSelectBuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectBuenoActionPerformed
        try {
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("ID");
            dtm.addColumn("Nombre");
            dtm.addColumn("Apellido");
            dtm.addColumn("Telefono");
            dtm.addColumn("Correo");
            dtm.addColumn("Calle");
            dtm.addColumn("Ciudad");
            dtm.addColumn("Estado");
            dtm.addColumn("C.P.");

            Connection con = DriverManager.getConnection(DBURL);
            PreparedStatement statement = con.prepareStatement(
                    "SELECT customer_id, first_name, last_name, phone, email, street, "
                    + "city, state, zip_code FROM sales.customers "
                    + "WHERE customer_id = ?");
            
            //statement.setInt(1, Integer.parseInt(this.txtId.getText()));
            statement.setString(1, this.txtId.getText());

            ResultSet rs = statement.executeQuery();

            while (rs.next()) {
                int str1 = rs.getInt(1);
                String str2 = rs.getString(2);
                String str3 = rs.getString(3);
                String str4 = rs.getString(4);
                String str5 = rs.getString(5);
                String str6 = rs.getString(6);
                String str7 = rs.getString(7);
                String str8 = rs.getString(8);
                String str9 = rs.getString(9);
                dtm.addRow(new Object[]{str1, str2, str3, str4, str5,
                    str6, str7, str8, str9});
            }

            this.tabla.setModel(dtm);
            rs.close();
            statement.close();
            con.close();
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "No no no :P", "Traviesillo",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSelectBuenoActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Connection con = DriverManager.getConnection(DBURL);
            PreparedStatement statement = con.prepareStatement(
                    "UPDATE sales.customers SET first_name = ? "
                    + "WHERE customer_id = ?");
            statement.setString(1, this.txtNuevoNombre.getText());
            statement.setString(2, this.txtIdUpdate.getText());

            int res = statement.executeUpdate();

            if (res == 0) {
                JOptionPane.showMessageDialog(this, "No se actualizo NADA",
                        "Update",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Se actualizaron "
                        + res + " registros.",
                        "Update",
                        JOptionPane.INFORMATION_MESSAGE);
            }
          
            con.close();
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "No no no :P", "Traviesillo",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSPInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPInsertActionPerformed
        try {
            Connection con = DriverManager.getConnection(DBURL);
            CallableStatement statement = con.prepareCall(
                    "{CALL dbo.sp_add_category(?,?)}"
            );
            statement.setString(1, this.txtCategoria.getText());
            statement.registerOutParameter(2, java.sql.Types.VARCHAR);

            statement.executeUpdate();

            JOptionPane.showMessageDialog(this, statement.getString(2),
                        "Insert",
                        JOptionPane.INFORMATION_MESSAGE);
            
            CallableStatement call = con.prepareCall(
                    "{CALL dbo.sp_get_categories()}"
            );
            
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("ID");
            dtm.addColumn("Categoria");
            
            ResultSet rs = call.executeQuery();

            while (rs.next()) {
                int str1 = rs.getInt(1);
                String str2 = rs.getString(2);
                dtm.addRow(new Object[]{str1, str2});
            }

            this.tabla.setModel(dtm);
            rs.close();
            call.close();
            statement.close();
            
            con.close();
        } catch (SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "No no no :P", "Traviesillo",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSPInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSPInsert;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnSelectBueno;
    private javax.swing.JButton btnSelectMalo;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdUpdate;
    private javax.swing.JTextField txtNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
